### ISSUE TITLE
Community Link Expired

### ISSUE THREAD

**Issue by michaeltoohig** [fleetbase/fleetbase#104]
**Describe the improvement**
The documentation navbar item "Community" contains an expired link to join your discord server.
The link is currently https://discord.gg/V39d5X9z

**Related Page**
In the navbar.

**Additional context**
N/A

**Comment by michaeltoohig** [comment]
The link https://discord.gg/MJQgxHwN in your README is also expired.

**Comment by roncodes** [comment]
It's been updated, thanks for looking out!

**Comment by michaeltoohig** [comment]
I found the invite on your main website footer did work, not sure if due to update or just a different invite link than the others so one more place to check in the future.
