### ISSUE TITLE
Documentation for Live Server deployment

### ISSUE THREAD

**Issue by Qoyyuum** [fleetbase/fleetbase#116]
**Is your feature request related to a problem? Please describe.**
Just tested and tried to deploy to production with docker-compose up -d but there's no way to map which port goes to which service or subdirectory to a domain name. This fails CORS policy and SSL Certificates.

**Describe the solution you'd like**
Perhaps include Traefik or NGINX Reverse Proxy and have it taken from an environment variable of whatever the domain name it is setting up against.

**Describe alternatives you've considered**
I've not considered other alternatives. I do not know much about how PHP and Composer installs work.

**Additional context**
So far, its running successfully in a Docker compose set up in Ubuntu 22.0.

**Comment by roncodes** [comment]
You can specify which/what port you'd like to assign to services using a `docker-compose.override.yml` see https://docs.docker.com/compose/multiple-compose-files/merge/

For example if you wanted to change the port which the socket exposes on you'd set it like so

```yaml
version: "3.8"

services:
  socket:
    ports:
      - "9000:8000"
```

This will expose the socket service on port 9000

**Comment by Qoyyuum** [comment]
Thank you so much! I didn't know about the docker compose override part. I think I'll be able to handle it from here 😄
