### ISSUE TITLE
websocket connection error

### ISSUE THREAD

**Issue by azharahmed123** [fleetbase/fleetbase#129]
socketcluster-client.min.js:106 WebSocket connection to 'wss://fleetbase.domain.com:38000/socketcluster/' failed:

**Comment by azharahmed123** [comment]
how to slove socket connection problem?

**Comment by roncodes** [comment]
Make sure your socketcluster instance is online by visiting the address first you should see a socketcluster landing page if it's online. From this page you can see the web console for connection hints.

**Comment by azharahmed123** [comment]
didnt get it. I would greatly appreciate it if you could clarify my question. Thank you very much for your assistance

**Comment by azharahmed123** [comment]
it was working on my localhost but when i put ssl on it everything is working fine accept this websocket
