### ISSUE TITLE
Fleetbased cloning error

### ISSUE THREAD

**Issue by stefanojj** [fleetbase/fleetbase#137]
i tried cloning fleetbase but i ended up with the following error

Cloning into 'fleetbase'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

how to resolve it?

**Comment by jittupant** [comment]
try this https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey

**Comment by Arafullahi** [comment]
try with adding new ssh key
