### ISSUE TITLE
Quote Management System For Orders.

### ISSUE THREAD

**Issue by stockarea** [fleetbase/fleetbase#149]
For each order, vendor can gives quotes which can have different statuses and remarks and can be accepted, rejected or put on hold based on the quote. We can have then accepted price and quote price per order ( or a trip)

**Comment by roncodes** [comment]
I think this is better off moved to the discussions section, with enough support we can consider this. Otherwise by April we will have our revamped documentation which will detail how to make custom extensions and customizations to existing extensions.
