### ISSUE TITLE
docker compose build is failing  while pnpm install 

### ISSUE THREAD

**Issue by Arafullahi** [fleetbase/fleetbase#151]
docker compose build is failing while pnpm install 

**To Reproduce**
took latest master branch code 
run dockercompose build

#0 22.46  ERR_PNPM_FETCH_401  GET https://npm.pkg.github.com/download/@fleetbase/fleetops-data/0.1.1/5de00fb4d99013cc86ecc55f85e8086bbfa56b30: Unauthorized - 401
#0 22.46
#0 22.46 No authorization header was set for the request.
#0 22.46 
#0 22.46 No authorization settings were found in the configs.
#0 22.46 Try to log in to the registry by running "pnpm login"
#0 22.46 or add the auth tokens manually to the ~/.npmrc file.

**Expected behavior**

**Screenshots**

**Logs (if relevant)**
Any log relevant log messages or snippets

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by roncodes** [comment]
This should be fixed in the last release but if you're still encountering this issue a hotfix solution run this

```bash
cd console && rm pnpm-lock.yaml && pnpm install && cd ..
```

then retry `docker-compose up -d`

**Comment by GMJSilmaro** [comment]
Hi i still get this error any idea how to fix this?

![image](https://github.com/fleetbase/fleetbase/assets/73065462/eeaf3faf-c940-45af-a58e-123d9a52d14a)

**Comment by GMJSilmaro** [comment]
Hi, I still get this error @roncodes  
![image](https://github.com/fleetbase/fleetbase/assets/73065462/80043904-c9df-4a4b-94ac-7b353d31f48e)
