### ISSUE TITLE
unable to connect to socket server

### ISSUE THREAD

**Issue by freakster00** [fleetbase/fleetbase#152]
How do i solve this issue?

**Comment by freakster00** [comment]
![image](https://github.com/fleetbase/fleetbase/assets/121386692/b413754a-d0bd-4ed3-8dc8-39737c16bbe0)
![image](https://github.com/fleetbase/fleetbase/assets/121386692/de749db2-b64f-40b1-8152-eff7ce204522)

**Comment by freakster00** [comment]
@roncodes can you help me here

**Comment by roncodes** [comment]
Are you running with docker? If so can you confirm that the socketcluster container is online? Or share the logs from the container?

**Comment by freakster00** [comment]
@roncodes yes socketcluster is running 
![image](https://github.com/fleetbase/fleetbase/assets/121386692/5d5a445f-4f27-400a-a673-82c2c0c9e5f0)
But the problem is /socketcluster route is not getting found

**Comment by Arafullahi** [comment]
@freakster00 try to rum the console in without the Docker check the status

**Comment by roncodes** [comment]
You cannot connect to secure socket from localhost
