### ISSUE TITLE
customer can bypass email verification 

### ISSUE THREAD

**Issue by Arafullahi** [fleetbase/fleetbase#153]
**Describe the bug**
without entering the verify code customer can login

**To Reproduce**
1. Go to create new account 
2. once registration form completed
3. then remove all uri except the base url redirecting to dashboard

**Expected behavior**

**Screenshots**

**Logs (if relevant)**
Any log relevant log messages or snippets

**Desktop :**

**Comment by freakster00** [comment]
How can i connect you ?
@Arafullahi

**Comment by roncodes** [comment]
If you're using a self hosted version you need to first create an account to configure email for verification to be enabled otherwise it will bypass by default.

Alternatively you can configure email through the application config for verification to work.

**Comment by Arafullahi** [comment]
@roncodes even it was issue available in https://console.fleetbase.io/ also..

**Comment by roncodes** [comment]
Fixed now.
