### ISSUE TITLE
Import orders with Spreadsheets section missing a template and unable to exit the popup modal

### ISSUE THREAD

**Issue by nikhil-potterstech** [fleetbase/fleetbase#157]
**Describe the bug**
No template available, and not able to exit "Import order(s) with Spreadsheets" modal popup if I don't have anything to upload.
Close button, keyboard Esc button, clicking outside not working.

**To Reproduce**
1. Go to 'Create New Order'
2. Click on 'Import' button in top right
3. Modal popup opens.
4. There is no link / button to download any template - how can end user know which are the correct columns to put in the spreadsheet ?
5. If we don't submit any file and try to go back to the dashboard, we're not able to. Close button, Esc keyboard button, clicking outside the popup - nothing works.
6. The browser console is showing some errors, see in screenshot

**Expected behavior**
1. Modal popup should show a link or button to download a template spreadsheet which we can then populate with our orders
2. Upon attempting to exit from the popup and return to dashboard, user should be able to by clicking close button, pressing Esc, or clicking somewhere outside (any 1 or more of these)

**Screenshots**
![image](https://github.com/fleetbase/fleetbase/assets/151506663/8c4e5a5d-ff46-4ace-ada2-5f6b05c8ee50)

**Logs (if relevant)**
See console log in screenshot

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1 Cinnamon
 - Browser: Brave
 - Version: Version 1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit) (https://brave.com/latest/)

**Comment by roncodes** [comment]
Patched in 0.3.2
