### ISSUE TITLE
Added Places don't show up in Pickup, Dropoff or Return dropdowns in Create New Order form > Route section 

### ISSUE THREAD

**Issue by answerquest** [fleetbase/fleetbase#161]
**Describe the bug**
Even after onboarding Places, they don't appear in the pickup 

**To Reproduce**
1. Go to Places section under Fleet-Ops and add some Places
2. Click on 'Create New Order'
3. Scroll down to Route section
4. Try to add one of the places under Pickup, Dropoff or Return - they don't appear in the dropdown.

**Expected behavior**
The Places that we have onboarded in the Places section should appear in the Pickup, Dropoff or Return dropdowns in Create New Order form > Route section.

**Screenshots**
Places section: 
![image](https://github.com/fleetbase/fleetbase/assets/151506663/94e2a263-d786-4323-a155-bdfaebf4da91)

Create New Order Form > Route section
![image](https://github.com/fleetbase/fleetbase/assets/151506663/5988e9bd-ed36-4a28-b287-86a6168188f6)

**Logs (if relevant)**
For any of those dropdowns opened, GET api calls are made to backend endpoint:
/int/v1/places/search?geo=true&latitude=18.5204&longitude=73.8567&query=P

But this might be going to google places search or so? We may be having some other api for searching among the already onboarded Places?

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Brave Browser
 - Version: v1.60.118

**Additional context**

**Comment by roncodes** [comment]
Patched in 0.3.2
