### ISSUE TITLE
API endpoints thorw 500 errors

### ISSUE THREAD

**Issue by miquelfa** [fleetbase/fleetbase#167]
**Describe the bug**
Just deployed the stack using Docker Compose. The API is throwing 500 errors on the auth screen. Specifically the following endpoints:
- :8000/int/v1/settings/branding
- :8000/int/v1/installer/initialize

Cannot create account, login or do anything else. Connection to wss also fails.

**To Reproduce**
1. Deploy following the guide
2. Use the stack out of the box
3. (optional) Add extra config to correct CORS error
4. Go to http://url:4200 and see the 500's coming through DevConsole

**Comment by roncodes** [comment]
Sounds like you didn't run migrations. See troubleshoot section.
