### ISSUE TITLE
Unable to create new tracking status

### ISSUE THREAD

**Issue by yogeshwarp** [fleetbase/fleetbase#169]
**Describe the bug**
I am trying to create a demo for last mile for eCommerce site (for demo purpose). Have created a flow where order will be pushed into fleetbase via orders API (which is working fine). As a next step we are trying to push few tracking statuses to show the journey of the order but the endpoint /tracking-statuses (POST) is failing. fetching existing statuses from this endpoint works fine.

**To Reproduce**
1. Call the /v1/tracking-statuses POST method via Postman
2. Following error is shown.     "errors": [
        "SQLSTATE[HY000]: General error: 1364 Field 'location' doesn't have a default value (SQL: insert into `tracking_statuses` (`company_uuid`, `uuid`, `public_id`, `_key`, `updated_at`, `created_at`) values (6ec6b480-2009-4741-b6b1-e3076e037cd3, fc3449d6-5b29-488e-b930-f72929266783, status_y3BB0GR, console, 2023-12-18 04:24:44, 2023-12-18 04:24:44))"
    ]
3. Have used a following sample payload
{
    "city":"Pune, MH",
    "code": "CREATED",
    "country": null,
    "details": "New order created.",
    "location": {
        "coordinates": [
            0,
            0
        ],
        "type": "Point"
    }
}

**Expected behavior**
New tracking status has been created.

**Screenshots**

**Logs (if relevant)**
Any log relevant log messages or snippets

This is happening on a local setup created from main branch with pull from 2 days back. If I try similar API request on cloud setup I get following error
{"errors":["Failed to create tracking status"]}

**Comment by roncodes** [comment]
Patched in release 0.3.2
