### ISSUE TITLE
Problem in Update Bussiness and Waypoints in Create Order

### ISSUE THREAD

**Issue by matheus-arruda** [fleetbase/fleetbase#171]
When trying to update a company, I receive the error from the API below

`{"errors":["Invalid param \"place_uuid\" in update request!"]}`

![Screenshot 2023-12-20 074722](https://github.com/fleetbase/fleetbase/assets/19500102/780dc506-4da8-4e06-8b84-342824f89517)

And when creating a new order, when I click on multiple dropoff`s I receive an error in the console and the input to select is not displayed.

`Uncaught (in promise) TypeError: Cannot destructure property 'manager' of 'e' as it is null.`\

![Screenshot 2023-12-20 074841](https://github.com/fleetbase/fleetbase/assets/19500102/f3c2d2a5-0a4c-4614-a32b-3490a675f450)

Other Informations
I followed the steps for installation, executed the migrations.
I use Docker on Windows and the defined branch is main.

**Comment by roncodes** [comment]
Both issues will be patched in upcoming release tomorrow

**Comment by matheus-arruda** [comment]
> Both issues will be patched in upcoming release tomorrow

Thanks, have a nice day.
