### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by matheus-arruda** [fleetbase/fleetbase#173]
Is there any development documentation?

At the same time, another question.
I tried to change the menu a little, I changed it in the file

`fleetbase\packages\fleetops\addon\components\layout\fleet-ops-sidebar.js`

However, when I upload the application again to Docker, the menu remains the same. 
_I accessed Docker to check the files and there it was with my changes, but it didn't reflect on the web page_

**Comment by roncodes** [comment]
To setup a development environment especially for the console, you need to disable running the console in docker. 

You can use these steps to setup development environment.

Open `console/package.json` find the package you want to make changes to. For example if you want to make changes to fleetops, you will change the following:

```json
{
    "dependencies": {
         "@fleetbase/fleetops-engine": "^0.1.14", 
     }
}
```
change to ->
```json
{
    "dependencies": {
         "@fleetbase/fleetops-engine": "link:../packages/fleetops", 
     }
}
```

Next run "pnpm install && pnpm start"

This will start the console in development environment, all changes you make to `packages/fleetops` will reload the console and reflect.
