### ISSUE TITLE
Cannot update product data

### ISSUE THREAD

**Issue by pelDev** [fleetbase/fleetbase#177]
**Describe the bug**
Cannot update or delete created products i n the fleetbase system

**To Reproduce**
1. Create a store and create products
2. Try to update the product Image or any other detail
3. See error

**Expected behavior**
Product to be updated with new data.

**Screenshots**
<img width="1440" alt="Screenshot 2023-12-29 at 03 55 13" src="https://github.com/fleetbase/fleetbase/assets/64491644/1bcd6e6d-caf4-4688-a5ef-9e0018c82ca3">

**Logs (if relevant)**
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_by_uuid' in 'field list' (SQL: update product_variants set product_uuid = ?, created_by_uuid = ?, company_uuid = ?, name = Package, description = Type container for the juice, is_multiselect = 0, is_required = 1, created_at = 2023-12-29T02:20:51.000Z, product_variants.updated_at = 2023-12-29T02:20:51.000Z where uuid = 4fb47c0d-87cc-4cc8-9618-db168bb0b326 and product_variants.deleted_at is null) 

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 120.0.6099.129 (Official Build) (x86_64)

**Comment by roncodes** [comment]
This issue is resolved in the latest release v0.3.5
