### ISSUE TITLE
Link vehicle to order

### ISSUE THREAD

**Issue by ddouma** [fleetbase/fleetbase#216]
Hello,

Currently you can link a driver to an order (great!), but it would also be relevant to link a vehicle to the order.

This because you can have alot of drivers that can drive mulitple vehicles.

Thanks!

**Comment by roncodes** [comment]
We've added this to the roadmap, will likely be introduced in v0.4.7

**Comment by roncodes** [comment]
Still on the roadmap... now maybe v0.4.14

**Comment by roncodes** [comment]
Release in v0.4.22
