### ISSUE TITLE
App linking

### ISSUE THREAD

**Issue by ddouma** [fleetbase/fleetbase#217]
Currently the app linking via de link in Fleetbase is not working.

It woupd be nice that you can manual edit the 'instance configuration' in the app. This would take away alot of issue's.

![Screenshot_20240220_152709](https://github.com/fleetbase/fleetbase/assets/16834930/64adc28e-be2d-4e74-abbb-3b8c84eac0a6)

**Comment by roncodes** [comment]
We cannot allow this for security reasons, but the fix for instance linking is in v0.4.10
