### ISSUE TITLE
Problem when create a account with Fleetbase Console

### ISSUE THREAD

**Issue by linhduongpscd** [fleetbase/fleetbase#226]
Hello. 

I have some problem when I try to create account in fleetbase console. 

I already run the migration and seeder and can redirect and access to 'Create your account' page of Fleetbase console. But when submit to create a account, it's show the popup 'Opps! Something when wrong when handling your request', and when I check the Network fetch it response code 500 Server Error.

![image](https://github.com/fleetbase/fleetbase/assets/30916987/4256f580-80ce-4de5-a1ce-8b1c8a23e4d7)

**Comment by roncodes** [comment]
Try running `sh deploy.sh` from the application container. Otherwise try the troubleshoot section. Without any logs we can't help.
