### ISSUE TITLE
`The selected pod required is invalid` on order creation

### ISSUE THREAD

**Issue by woutkonings** [fleetbase/fleetbase#230]
**Describe the bug**
`The selected pod required is invalid` error on create order in console.fleetbase.io

**To Reproduce**
1. Go to create order and create an order
2. Click on Submit

**Expected behavior**
I expected the order to be created. I haven't been able to create a single order in Fleetbase yet.

**Screenshots**
![image](https://github.com/fleetbase/fleetbase/assets/25101891/ad0b5e25-e45b-4035-a8fc-90b8b8642d52)

**Logs (if relevant)**
`The selected pod required is invalid`

In console:
```
XHRPOST
https://api.fleetbase.io/int/v1/orders
[HTTP/2 422  321ms]

response: "The selected pod required is invalid."

```

**Comment by roncodes** [comment]
Fixed in latest release v0.4.12 -- deployed to cloud version
