### ISSUE TITLE
Idea: Tracking frontend, customer facing

### ISSUE THREAD

**Issue by plague69** [fleetbase/fleetbase#237]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
- WYSIWYG tracking page editor.
- Background and custom CSS.
- Level of detail selectable (exact driver location or just text status)

https://console.fleetbase.io/track?n=TA1684696 will display a tracking page with "[Custom block] + input box + track button + [custom footer]"

**Describe alternatives you've considered**
Write custom intergration pulling from the API

* If external 3rd party delivery, then a link can be displayed or user can be displayed instead. Of course that would mean that there should be an option for prefix and suffix to tracking number option for the 3rd

**Comment by roncodes** [comment]
On the roadmap for this quarter

**Comment by roncodes** [comment]
Released with v0.5.8
