### ISSUE TITLE
composer insertall error

### ISSUE THREAD

**Issue by chengyabing** [fleetbase/fleetbase#242]
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error

  Class "GEOSWKBReader" not found

  at vendor\brick\geo\src\Engine\GEOSEngine.php:39
     35▕     private bool $hasBinaryReadWrite;
     36▕
     37▕     public function __construct()
     38▕     {
  ➜  39▕         $this->wkbReader = new \GEOSWKBReader();
     40▕         $this->wkbWriter = new \GEOSWKBWriter();
     41▕
     42▕         $this->wktReader = new \GEOSWKTReader();
     43▕         $this->wktWriter = new \GEOSWKTWriter();

  1   vendor\fleetbase\fleetops-api\server\src\Providers\FleetOpsServiceProvider.php:100
      Brick\Geo\Engine\GEOSEngine::__construct()

  2   vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      Fleetbase\FleetOps\Providers\FleetOpsServiceProvider::boot()

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by roncodes** [comment]
Running from docker or on machine? If running on machine you'll need to install this pecl/php dependencies
