### ISSUE TITLE
console/pnpm-lock.yaml file is deleted and causes installation failure. 

### ISSUE THREAD

**Issue by alashti** [fleetbase/fleetbase#245]
**Describe the bug**
the console/pnpm.yaml file is deleted in the last commit ([ad055cc](https://github.com/fleetbase/fleetbase/commit/ad055cc4e6979776c000477b1f4f0f478b3503d4#diff-59a4b63aa013e77ab7dcd4049e68a0965b52330e2617991d6db3590c186095b1)) and the docker build fails. 

**To Reproduce**
just follow the installation steps. you will face it in the `docker-compose up -d` step. 

**Expected behavior**
the installation being completed successfully. 

**Screenshots**
![image](https://github.com/fleetbase/fleetbase/assets/6141719/e937f73b-cd84-4af2-9315-30e1da9ec5e0)

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04

**Comment by roncodes** [comment]
Fixed in last release
