### ISSUE TITLE
Unable to verify Email if Skipped for the first time

### ISSUE THREAD

**Issue by pawanmkr** [fleetbase/fleetbase#250]
**Describe the bug**
I filled the form for signup but didn’t entered verification code received on email immediately, instead i went back to login and entered credentials.

Now at login page it says email not verified(obviously), so it sent me an email with VERIFICATION_CODE but i was expecting a LINK because fleetbase console kept me on login page and not presenting the input field to enter VERIFICATION_CODE.
So, i cannot enter my verification code and verify my account.
I tried manually opening /onboard/verify-email page to enter code. It says session not found, so it requires a session also.

**To Reproduce**
1. Go to Create Account page and fill form.
2. When forwarded on next page to enter verification code, don't enter and get back to login page.
3. Enter email and password again which you used to create account in 1st step.
4. Now you'll receive verification code on email but notice that fleetbase console is not showing input field to enter verification code in this case.

**Expected behavior**
It should show the page with input field to enter verification code received on email.

**Screenshots**
<img width="1589" alt="Screenshot 2024-05-11 at 12 52 38 PM" src="https://github.com/fleetbase/fleetbase/assets/53852047/387c3b84-e070-47a0-bf64-cc10c45d0145">

<img width="1589" alt="Screenshot 2024-05-11 at 12 53 00 PM" src="https://github.com/fleetbase/fleetbase/assets/53852047/c852f77e-63bf-4237-80af-ff5bc8599798">

**Desktop (please complete the following information):**
 - OS: macOs 14.4.1
 - Browser: Thorium(based on chromium), but it's happeing in other browsers also like chrome
 - Version 119.0.6045.214 (Official Build) (arm64)

**Comment by roncodes** [comment]
Thanks for report, will patch next release

**Comment by roncodes** [comment]
Patched in v0.4.22
