### ISSUE TITLE
Installing Fleetbase in a server

### ISSUE THREAD

**Issue by nperezv** [fleetbase/fleetbase#251]
Hi there! Im using docker to install Fleetbase, I encounter that I'm allowed toi login only from the localhost:4200.

When I try to login and use it from another computer pointing to the ip address and port, I get the "Network request failed". I ve tried adding the line "allowed_hosts" array and putting there both ip from Im making the request and the ip server which holds the fleetbase image just for testing. I've also tried to putting the ip at the "allowed_origins" array and again just for testing but nothing is working, @roncodes please I need help with this. Thank you so much, I've also attached the content of both arrays and some logs:

cors.php arrays:
'allowed_origins' => array_filter(['http://localhost:4200', env('CONSOLE_HOST'), Utils::addWwwToUrl(env('CONSOLE_HOST')), 'http://192.168.1.133']),
'allowed_hosts' => ['192.168.1.133', '192.168.1.228'],    

Logs from localhost:
cache-1        | 1:M 14 May 10:56:54.851 * 100 changes in 300 seconds. Saving...
cache-1        | 1:M 14 May 10:56:54.851 * Background saving started by pid 15
cache-1        | 15:C 14 May 10:56:54.866 * DB saved on disk
cache-1        | 15:C 14 May 10:56:54.866 * RDB: 0 MB of memory used by copy-on-write
httpd-1        | 172.25.0.1 - - [14/May/2024:10:56:54 +0000] "GET /int/v1/auth/session HTTP/1.1" 200 116 "http://localhost:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
cache-1        | 1:M 14 May 10:56:54.951 * Background saving terminated with success
httpd-1        | 172.25.0.1 - - [14/May/2024:10:56:55 +0000] "OPTIONS /int/v1/users/me HTTP/1.1" 204 0 "http://localhost:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
httpd-1        | 172.25.0.1 - - [14/May/2024:10:56:55 +0000] "GET /int/v1/users/me HTTP/1.1" 200 496 "http://localhost:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
httpd-1        | 172.25.0.1 - - [14/May/2024:10:56:55 +0000] "OPTIONS /int/v1/settings/branding HTTP/1.1" 204 0 "http://localhost:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
httpd-1        | 172.25.0.1 - - [14/May/2024:10:56:55 +0000] "GET /int/v1/settings/branding HTTP/1.1" 200 272 "http://localhost:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

Logs from other machine:
console-1      | 192.168.1.133 - - [14/May/2024:10:57:31 +0000] "GET /auth HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

**Comment by roncodes** [comment]
You need to set the `API_HOST` to your server in the correct environment file `console/environments/*.env`

**Comment by nperezv** [comment]
> _HO

I appreciate your help. I'm brand new to this, the route and file you are talking about is located inside the container? Or I could change it in the folder "console/environments/*..." crom the cloned repo? I was looking for it inside the docker container but could   not find it. Thank you so much again!

**Comment by nperezv** [comment]
Finally I could find it and yes `API_HOST` is pointiign to the server ip but it still not working. Again, thanks for your help!

```
API_HOST=192.168.1.228:4200
API_NAMESPACE=int/v1
API_SECURE=true
SOCKETCLUSTER_PATH=/socketcluster/
SOCKETCLUSTER_HOST=
SOCKETCLUSTER_SECURE=true
SOCKETCLUSTER_PORT=38000
OSRM_HOST=https://bundle.routing.fleetbase.io
OSRM_SERVERS=https://canada.routing.fleetbase.io,https://us.routing.fleetbase.io
```
