### ISSUE TITLE
Network request failure when trying to login from other machine

### ISSUE THREAD

**Issue by nperezv** [fleetbase/fleetbase#252]
Finally I could find it and yes `API_HOST` as you mentioned before, so it  is pointign to the server ip but it still not working. Again, thanks for your help!

```
API_HOST=192.168.1.228:4200
API_NAMESPACE=int/v1
API_SECURE=true
SOCKETCLUSTER_PATH=/socketcluster/
SOCKETCLUSTER_HOST=
SOCKETCLUSTER_SECURE=true
SOCKETCLUSTER_PORT=38000
OSRM_HOST=https://bundle.routing.fleetbase.io
OSRM_SERVERS=https://canada.routing.fleetbase.io,https://us.routing.fleetbase.io
```

_Originally posted by @nperezv in https://github.com/fleetbase/fleetbase/issues/251#issuecomment-2109983440_

**Comment by roncodes** [comment]
The API will be on port 8000 your frontend is port 4200 so your `API_HOST` must be `=192.168.1.228:8000`
