### ISSUE TITLE
Not able to add location with new company setup

### ISSUE THREAD

**Issue by ShanConsulting** [fleetbase/fleetbase#255]
**Describe the bug**
Not able to create a location in the store front app.

**To Reproduce**
1. Signup with a new account on fleetbase
2. Login to console app (https://console.fleetbase.io/)
3. Go to https://console.fleetbase.io/storefront/settings
4. Add general settings with all mandatory fields
5. Go to 'https://console.fleetbase.io/storefront/settings/locations'
6. Click on 'Create new location'
7. Fill all the fields
8. Click on 'Add new Location'
9. See error in the screenshots section.

**Expected behavior**
The location should be saved and a valid success message to be returned.

**Screenshots**
<img width="495" alt="add_location_error" src="https://github.com/fleetbase/fleetbase/assets/122163783/9247ad69-9a31-4243-8e09-ff9a0986f6e8">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 124.0.6367.119

**Comment by roncodes** [comment]
Please see troubleshoot guide then try again https://docs.fleetbase.io/getting-started/troubleshoot
