### ISSUE TITLE
Customer shipment management 

### ISSUE THREAD

**Issue by giucloud** [fleetbase/fleetbase#265]
Allow the customer access to a portal, or fleetbase with a customer role and to be able to create and request services , track your services, be able to set up cash on delivery, a wallet to manage the balance and track your services, be able to ship from one point A to B, or from one city to another and it is deducted from your balance, be able to print shipping labels, and request pickup, And if possible also add it to storefront for a more focus on parcel and delivery businesses

**Comment by roncodes** [comment]
Customer Portal Extension was just released in v0.5.8
