### ISSUE TITLE
IAM: There is no option to assign a 'role' to either a 'group' or a 'user' or 'both'. That would be the ideal purpose of creating roles, right? Can this mapping be addressed pls? Thank you.

### ISSUE THREAD

**Issue by ittiar** [fleetbase/fleetbase#274]
**Describe the bug**
IAM: There is no option to assign a 'role' to either a 'group' or a 'user' or 'both'. That would be the ideal purpose of creating roles, right? Can this mapping be addressed pls? 

**To Reproduce**
1. Go to 'IAM, Roles menu'
2. Click on 'Create Roles'
3. There is no option to associate the role to a Group.

**Expected behavior**
In the Create Roles option, we should have the drop-down menu to associate the role to a Group.

**Screenshots**

**Logs (if relevant)**
Any log relevant log messages or snippets

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by roncodes** [comment]
This has been implemented and fixed in release https://github.com/fleetbase/fleetbase/releases/tag/v0.5.5
