### ISSUE TITLE
Build time of console is taking more than 1h.

### ISSUE THREAD

**Issue by ALGOSIGHT** [fleetbase/fleetbase#275]
Hi Team,

I trust you are well.
i m facing a challenge to optimize the time it took to build the console whenever i made a small change i need to wait for more than 1h to see the result. is there a way to run the build faster in ember.

Kind Regards,

**Comment by roncodes** [comment]
Are you running `ember serve` or manually rebuilding after a change?

There is a new build system available called embroider which is faster and more efficient, but unfortunately we have not adopted it yet and still use broccoli for build.

We plan to migrate to embroider in later versions.

**Comment by ALGOSIGHT** [comment]
i will try it and let you know. thanks
