### ISSUE TITLE
Changes to console environment files not being respected by console app 

### ISSUE THREAD

**Issue by SirDannyMunn** [fleetbase/fleetbase#278]
**Describe the bug**
When I deploy the app, and make changes to .env files, docker environment configs, or even directly in the environment.js file, the base url for doesn't change and still points to localhost:8000, instead of the prod URL i'm trying to change it to. 

**To Reproduce**
Modify env files
Install/build docker image 
Visit app in browser
attempt login
see network panel in devtools.

**Expected behavior**
The base url should change to the one set in the environment files

**Logs (if relevant)**
Any log relevant log messages or snippets

**Desktop (please complete the following information):**
 - OS: Ubuntu, windows
 - Browser, Chrome
 - Version: latest/master

**Comment by roncodes** [comment]
For the console you need to configure environment in `console/environments/.env.{environment}` then rebuild the app or image, see more here https://docs.fleetbase.io/getting-started/install/from-source#10-configure-fleetbase-console
