### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by mhamzamuneeb** [fleetbase/fleetbase#280]
![image](https://github.com/user-attachments/assets/9dc32edf-26cf-4ed8-b042-cded6e379fb8)

when i run the [fleetbase-httpd:0.3.4-cors](app://dd/dashboard/images/local/details?image=yogeshwarp2%2Ffleetbase-httpd%3A0.3.4-cors&imageId=sha256%3A46abf7d5421cde1390d3a92d5393c5d56a8a126213674e0734c50f39be50d478) it will show the error

**Comment by roncodes** [comment]
This is an outdated version and an unofficial image
