### ISSUE TITLE
Driver assigned to Admin user account

### ISSUE THREAD

**Issue by sbhanji** [fleetbase/fleetbase#281]
**Describe the bug**
When a creating a new driver without assigning a user account automatically assigns the Admin account tot the driver. The result of this  behavior then the Admin account's type to driver thus removing the Admin ability from the console 

**To Reproduce**
1. Create a new Driver without assigning a User Account 
2. Log out of Fleetbase
3. Login back into Fleetbase as the Admin account
4. The Admin menu item is no longer available, The Admin user is now changed to "driver" in the database from "admin"

**Expected behavior**
The new Driver should not be assigned the Admin's user account automatically. I believe for those deployment whose drivers dont carry mobile phones, and whose order activity are manually managed dont require user accounts or be forced to verify the driver.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: chrome
 - Browser Version: 127

**Additional context**
I had to manually change the Admin user's status back to admin in order to restate the Admin menu

**Comment by roncodes** [comment]
Thanks for the bug report, will be implementing a patch in an upcoming release

**Comment by roncodes** [comment]
This has been patched in release https://github.com/fleetbase/fleetbase/releases/tag/v0.5.5
