### ISSUE TITLE
CSS Style Issue

### ISSUE THREAD

**Issue by mhamzamuneeb** [fleetbase/fleetbase#285]
the fleetbase started successfully but there is an issue appearing on the  localhost:4200
![image](https://github.com/user-attachments/assets/3b9561ca-f778-463a-b9aa-458a9b8e3972)
all the css is not working
as if there is no css in it, all the layout is distorted and some of the api are not working also, somehow i have created an account but the issue still remains 
can you please help me in this matter
![image](https://github.com/user-attachments/assets/57b68793-0a8b-4a7e-866a-ce03252e506c)
![image](https://github.com/user-attachments/assets/e29416b5-f205-46df-88fb-4db46263da19)
![Uploading image.png…]()

**Comment by roncodes** [comment]
The screenshots are no help since your console is filtering to requests. Would at-least need to see the stylesheet/css request and the actual console.
