### ISSUE TITLE
Frontend Editing

### ISSUE THREAD

**Issue by mhamzamuneeb** [fleetbase/fleetbase#291]
Hi Fleetbase Team!
I wants to do some changes in the Frontend code of the fleetbase, but I coudnlt find any lead to do the changes
I have also checked the files in the Console Image of Docker but still couldnt find any lead
Can you please help me in this issue
Thanks

**Comment by roncodes** [comment]
You will need to provide more details on what frontend changes you'd like to make for us to help guide you. Please see the development setup guide first https://docs.fleetbase.io/getting-started/install/for-development
