### ISSUE TITLE
problems with the application build

### ISSUE THREAD

**Issue by kerolayne** [fleetbase/fleetbase#297]
Hello, I'm working on my thesis, and I need a supply chain to validate my proposal I chose your tool because, since it works with Docker, it helps me a lot in my process, but I've been having problems with the implementation in my environment. When I give the command "docker-compose up -d" I get the error attached to the image. So I would like your help to know if it's just me and what I can do to fix this problem.

Note: I have already checked, and the file "ember-leaflet@5.1.3.patch" is really in the indicated path

![Captura de tela 2024-10-02 184203](https://github.com/user-attachments/assets/0654eb15-f6af-4851-a208-a2128f691dc4)

**Comment by roncodes** [comment]
Can you provide your OS, and if any changes were made to the `docker-compose.yml` file?

**Comment by kerolayne** [comment]
I'm using Ubuntu 22.04.5, and this error occurs with the version of docker-compose.yml available on git hub

**Comment by roncodes** [comment]
Ok found an issue in the release will have patch in next release. 

But to fix your immediate issue you will need to edit line 18 of `console/Dockerfile.server-build` (see https://github.com/fleetbase/fleetbase/blob/main/console/Dockerfile.server-build#L18)

Change the line from

```
COPY console/package.json console/pnpm-lock.yaml ./
```

To:

```
COPY console/package.json console/pnpm-lock.yaml console/patches ./
```

This should resolve the issue. 

We will be getting rid of this patch in next release.

**Comment by kerolayne** [comment]
Unfortunately this change has not yet resolved the issue.

**Comment by roncodes** [comment]
Fixed in last release v0.5.9

**Comment by kerolayne** [comment]
Hello, the build was a success, now I'm trying to test the tool, and I can't create a user, when I click to create the user nothing happens, do you have a predefined user or a test base, my thesis is related to a security framework applied in the context of supply chain with IoT, and it would be very good for testing if there was already a generic base for testing

**Comment by roncodes** [comment]
Were you able to run the `sh deploy.sh` command from the application container?

See https://docs.fleetbase.io/getting-started/install/with-docker#5-run-the-deployment-script

**Comment by kerolayne** [comment]
Where can I find this file? because when I tried to run this command in the fleetbase root directory it returned that it could not be found

**Comment by roncodes** [comment]
The path in the container will be `/fleetbase/api/deploy.sh` 

https://github.com/fleetbase/fleetbase/blob/main/api/deploy.sh

**Comment by kerolayne** [comment]
When I use the sh deploy.sh command, it returns the following error "could not open input file: artisan" I installed and configured laravel but it doesn't work, is there anything specific I need to do?
