### ISSUE TITLE
ERR_PNPM_FETCH_403

### ISSUE THREAD

**Issue by jeetenkumarsingh** [fleetbase/fleetbase#305]
Getting ERR_PNPM_FETCH_403

 ERR_PNPM_FETCH_403  GET https://registry.fleetbase.io/@fleetbase/ember-core/-/ember-core-0.2.17.tgz: Forbidden - 403

This error happened while installing a direct dependency of /fleetbase/console

An authorization header was used: Bearer [hidden]

These authorization settings were found:
//registry.fleetbase.io/:_authToken=[hidden]
@fleetbase:registry=https://registry.fleetbase.io/

**Comment by roncodes** [comment]
Use the latest version.

**Comment by jeetenkumarsingh** [comment]
I downloaded latest version, still getting same error.

**Comment by roncodes** [comment]
Remove the authorization settings.

**Comment by jeetenkumarsingh** [comment]
where is this authorization settings ?

**Comment by jeetenkumarsingh** [comment]
Can you please help me and guide, how to resolve this issue. It was working fine in last version.

**Comment by roncodes** [comment]
> //registry.fleetbase.io/:_authToken=[hidden]
> @fleetbase:registry=https://registry.fleetbase.io/

Clearly some additional settings have been added in some `.npmrc` file and it's being picked up.

**Comment by NeverMin** [comment]
```
 ERR_PNPM_FETCH_403  GET https://registry.fleetbase.io/@fleetbase/dev-engine/-/dev-engine-0.2.9.tgz: Forbidden - 403

No authorization header was set for the request.

These authorization settings were found:
@fleetbase:registry=https://registry.fleetbase.io
The command '/bin/sh -c pnpm install' returned a non-zero code: 1
ERROR: Service 'console' failed to build : Build failed
never@localhost:~/fleetbase$ 
never@localhost:~/fleetbase$ 
never@localhost:~/fleetbase$ 
never@localhost:~/fleetbase$ git status
HEAD detached at v0.5.18
nothing to commit, working tree clean
```
