### ISSUE TITLE
Unable to save Service Area or Zone

### ISSUE THREAD

**Issue by shivthakker** [fleetbase/fleetbase#318]
**Describe the bug**
Creating a service area or zone not working. The dialogue box to save the Service area does not appear. 

**To Reproduce**
1. Go to Service Area
2. Click on 'New Service Area
3. Draw the polygon to create the service area
4.  Once you join the polygon there should be a pop up to save the service area but this does not happen. 

**Expected behavior**
Once you close the polygon, there should be the option to name and save the service area but does not happen. 

**Screenshots**
![image](https://github.com/user-attachments/assets/60b32950-c982-4871-8f23-f3932c733fce)

**Comment by roncodes** [comment]
Fixed in #320
