### ISSUE TITLE
Currencies missing Uganda Shillings

### ISSUE THREAD

**Issue by pkawalya** [fleetbase/fleetbase#323]
Dear Fleetbase Team,

Thank you for the great work. I have noticed that ugx currency is missing in the list of currencies when setting up a store
![Screenshot from 2024-11-28 09-53-18](https://github.com/user-attachments/assets/4e229b6f-43a6-4130-9f26-6144ddb19141)

**Comment by roncodes** [comment]
Will be added in next planned release

**Comment by pkawalya** [comment]
Thank you Ron

**Comment by konate58** [comment]
Dear Team,
also add XOF please.
Thanks

**Comment by roncodes** [comment]
Added in https://github.com/fleetbase/fleetbase/releases/tag/v0.5.19

**Comment by bkrzou** [comment]
> Added in https://github.com/fleetbase/fleetbase/releases/tag/v0.5.19

please add also DZD algerian dinar
