### ISSUE TITLE
Unable to update currency in org settings

### ISSUE THREAD

**Issue by shivthakker** [fleetbase/fleetbase#326]
**Describe the bug**
Unable to change the currency in the organisation settings

**To Reproduce**
Click and select organisation currency
Save
Refresh and it goes back to SGD (tried switching to MXN)

**Screenshots**
![image](https://github.com/user-attachments/assets/2991f0fa-2855-4fbe-b8aa-3ae9a10f1a7b)

**Comment by pkawalya** [comment]
Thank you for your response.

Going to try it again

**Comment by roncodes** [comment]
Added in https://github.com/fleetbase/fleetbase/releases/tag/v0.5.19
