### ISSUE TITLE
Country selection is selecting a different country 

### ISSUE THREAD

**Issue by rodrigolopezguerra** [fleetbase/fleetbase#330]
**Describe the bug**
When a customer or direction is created , it seems that "Argentina" it's mix up con selection . Could be general (make more sense)

**To Reproduce**
1. Go to Customers
2. Create a Customer and put country Argentina
3. The created image would show him on nowhere and country aruba

**Expected behavior**
Place the marker on Argentina

**Screenshots**
![3](https://github.com/user-attachments/assets/870161d3-b311-4fd1-8bbc-f4fbb242e57d)
![2](https://github.com/user-attachments/assets/4e3fd24c-9702-4335-bf2e-b4305b5634a8)
![1](https://github.com/user-attachments/assets/b92a6a93-afde-4f17-80d9-82af9b799506)

**Comment by roncodes** [comment]
Fixed in [#v0.5.19](https://github.com/fleetbase/fleetbase/releases/tag/v0.5.19)
