### ISSUE TITLE
git submodule update --init --recursive Permission error

### ISSUE THREAD

**Issue by pkawalya** [fleetbase/fleetbase#45]
**Permission error while deploying with docker**
Getting this error I try to run git submodule update --init --recursive

fatal: clone of 'git@github.com:fleetbase/storefront-api.git' into submodule path '/root/fleetbase/packages/storefront-api' failed
And for the other modules.

**Comment by roncodes** [comment]
This is a permissions error involving git, make sure your ssh keys on your local or server are setup with your github account. If everything is fine regarding your ssh keys you can try  to run 
```bash
git submodule sync
```
then
```bash
git submodule update --init --recursive
```

**Comment by gulbalee** [comment]
I had to change the .gitmodules file. Replaced https://github.com/fleetbase instead of git@github:fleetbase
