### ISSUE TITLE
Routing not working

### ISSUE THREAD

**Issue by ddouma** [fleetbase/fleetbase#48]
Hello,

An Issue. The routing is not working for The Netherlands (Europe).
As stated on Discord you use OSRM. If I go to https://project-osrm.org/ and try a routing there within the Netherlands it works.

So maybe running a local routing module on the same server we are running our Fleetbase instance on?

![image](https://github.com/fleetbase/fleetbase/assets/16834930/b3a5f9d6-f493-43a9-a876-61e7eafdb40d)
![image](https://github.com/fleetbase/fleetbase/assets/16834930/b1c41a6e-09ea-4c08-8bb1-49a477b9adb7)

**Comment by roncodes** [comment]
This is an idea but it isn't practical as building, hosting and running a routing machine / OSRM instance is very intensive and costly. For example building with the map data can take over 24 hours. This is why we do not include OSRM as part of the repo but encourage you to use a third party OSRM or wait until we enable third party routing capabilities like Mapbox, Google Maps and others.

If you have specific countries or regions you'd like to use with Fleetbase without switching the `OSRM_HOST` let us know in Discord and we will enable them.

**Comment by ddouma** [comment]
Hello Ron,

Could you please provide me with more info.
I thought the idea was the drivers could use the app of fleetbase to navigate? Like you display on your website:

![image](https://github.com/fleetbase/fleetbase/assets/16834930/18326bc4-d023-4721-90dd-e5075ba34739)

So i'm a bit confused right now. You say you don't include OSRM so I assume that you don't provide this option in the opensource version? I need the region/country: The Netherlands.

Or an option to config my own routing provider, OSRM, Google Maps and pay for it myself :).

**Comment by roncodes** [comment]
Additionally we will enable Netherlands which will take about 24 hours from tomorrow 9AM SGT.

**Comment by roncodes** [comment]
Additionally there is a published Driver app but unfortunately it's not compatible with the open source version yet. We plan to make this configurable and brandable to open source instances in the future.

**Comment by ddouma** [comment]
> Additionally we will enable Netherlands which will take about 24 hours from tomorrow 9AM SGT.

Hello, Still not working, do I have to change something in the config?

**Comment by ddouma** [comment]
Bumb! Still not working. Do I need to do anything?
