### ISSUE TITLE
SSL not working

### ISSUE THREAD

**Issue by ddouma** [fleetbase/fleetbase#49]
Hello,

SSL is not working. If I put https infront of the URL (IP) it show the error as shown below.
Because you run it on port 4200 and not the local apache webserver it doesn't load a proper SSL certificate.

Where do you store the SSL key file?

![image](https://github.com/fleetbase/fleetbase/assets/16834930/63a780df-1b98-4ccc-9361-f170dff242ae)

**Comment by roncodes** [comment]
You'll need to enable SSL yourself, this isn't a built in feature for Fleetbase at this moment. You can setup free SSL cert using letsencrypt see https://certbot.eff.org/instructions

**Comment by ddouma** [comment]
Hello, That's OK. That why i ask in what container and where do you store the webfiles / apache / nginx

**Comment by roncodes** [comment]
You can find the `nginx.conf` in the root of the repo.
