### ISSUE TITLE
Network Request Failed when onboarding

### ISSUE THREAD

**Issue by pkawalya** [fleetbase/fleetbase#52]
**Network Request Failed**
Thank you @roncodes  and @shivthakker  for the great work, I managed to successfully deploy the app. When trying to onboard a new user I get this error.

Kindly advise, am also trying to look at the logs

Thank you

**Comment by roncodes** [comment]
Please check the "Additional Steps" section under the Installation on the README to make sure you have CORS configured.

[Additional Steps](https://github.com/fleetbase/fleetbase#additional-steps)

**Comment by gulbalee** [comment]
Worked great for me. Tip for beginners like me --> go to console of fleetbase-application-1 container then `cd config` then `nano cors.php` change there then CTRL+O and CTRL+X. Restart container to get it working and access the site again.
