### ISSUE TITLE
Scheduler & vehicle option

### ISSUE THREAD

**Issue by ddouma** [fleetbase/fleetbase#57]
Hello!,

In the version on Fleetbase.io there are 2 options that are missing in the Github version:

Scheduler -> To see when a vehicle is in use
![image](https://github.com/fleetbase/fleetbase/assets/16834930/ad038554-9974-4eb8-89fb-16108502df9f)

Attach a Vehicle to an order. This is also missing.

**Comment by roncodes** [comment]
Yes these two versions are completely different. Due to dependency reasons we couldn't move the scheduler into the open source version right away, but it will be added later.
