### ISSUE TITLE
Branding logo's not working

### ISSUE THREAD

**Issue by ddouma** [fleetbase/fleetbase#60]
The branding option is not working. After clicking on upload it does not refresh the logo.
Error logs shows nothing.

**Comment by roncodes** [comment]
Can you check to make sure you have filesystem configured for uploads?

**Comment by ddouma** [comment]
Hello Ron,

Where to check?

**Comment by roncodes** [comment]
You'll need to access the admin. Look in the menu with your organization name and you'll see Admin, from there go to Filesystem under System Configuration.

**Comment by ddouma** [comment]
Hello Ron,

I tryed all 4 options, same effect:

![image](https://github.com/fleetbase/fleetbase/assets/16834930/f644168a-85c5-4a3a-9d82-6b28cb7b2a66)

**Comment by roncodes** [comment]
Please pull the latest and retry

**Comment by ddouma** [comment]
Still not working...

If I click on 'Upload New' -> Select image -> Then it goes back says quick uploading but still same logo

**Comment by echostorm** [comment]
Facing same issue!
