### ISSUE TITLE
Route calculating not working in Order page

### ISSUE THREAD

**Issue by ddouma** [fleetbase/fleetbase#74]
Hello,

The route calculating is working when you add an order:

![image](https://github.com/fleetbase/fleetbase/assets/16834930/79029f38-ab1d-4776-a131-2f5e225e0bf7)

But when you create the order and go back to the Order page it gets messed up again:

![image](https://github.com/fleetbase/fleetbase/assets/16834930/88aeb861-55a0-4519-b451-36babe57e737)

**Comment by roncodes** [comment]
See the new `update.sh` script, should resolve this issue with `v0.1.5`
